## Digits  : 손글씨를 분류해 봅시다

In [52]:
import pandas as pd 
from sklearn.datasets import load_digits
from sklearn.datasets import load_breast_cancer
from sklearn.datasets import load_wine

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,  confusion_matrix

### 데이터 준비 

In [5]:
digits = load_digits()
wine = load_wine()
breast_cancer = load_breast_cancer()

### 데이터 이해하기 

- Feature Data 지정하기
- Label Data 지정하기
- Target Names 출력해 보기
- 데이터 Describe 해 보기

#### feature 지정 

In [21]:
digits_data = digits.data
print(digit_data.shape)
digits_data[0]

(1797, 64)


array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

#### label 지정하기 

In [14]:
digits_label = digits.target
print(digits_label.shape)

digits_label

(1797,)


array([0, 1, 2, ..., 8, 9, 8])

#### target name

In [15]:
digits.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### digits describe 

In [17]:
print(digits.DESCR)

.. _digits_dataset:

Optical recognition of handwritten digits dataset
--------------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 5620
    :Number of Attributes: 64
    :Attribute Information: 8x8 image of integer pixels in the range 0..16.
    :Missing Attribute Values: None
    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)
    :Date: July; 1998

This is a copy of the test set of the UCI ML hand-written digits datasets
https://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits

The data set contains images of hand-written digits: 10 classes where
each class refers to a digit.

Preprocessing programs made available by NIST were used to extract
normalized bitmaps of handwritten digits from a preprinted form. From a
total of 43 people, 30 contributed to the training set and different 13
to the test set. 32x32 bitmaps are divided into nonoverlapping blocks of
4x4 and the number of on pixels are counted in each blo

### train, test 데이터 분리


In [28]:
X_train, X_test, y_train, y_test = train_test_split(digits_data, 
                                                    digits_label, 
                                                    test_size=0.3,
                                                    random_state=8)

print('X_train 개수: ', len(X_train), ', X_test 개수: ', len(X_test))

X_train 개수:  1257 , X_test 개수:  540


### 다양한 모델로 학습시켜보기

- Decision Tree 사용해 보기
- Random Forest 사용해 보기
- SVM 사용해 보기
- SGD Classifier 사용해 보기
- Logistic Regression 사용해 보기

### Decision Tree

In [71]:
from sklearn.tree import DecisionTreeClassifier

decision_tree = DecisionTreeClassifier(criterion='entropy',
                                       random_state=32)
                                       # max_depth= 8)
decision_tree.fit(X_train, y_train)
y_pred = decision_tree.predict(X_test)


print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[52  0  0  0  1  0  2  0  1  0]
 [ 0 44  2  2  1  6  0  2  0  2]
 [ 0  0 47  4  0  1  0  0  0  1]
 [ 0  1  0 49  0  3  1  1  3  4]
 [ 0  2  0  0 34  0  3  1  1  1]
 [ 0  2  1  0  0 56  1  0  0  2]
 [ 0  2  0  0  0  0 48  0  1  0]
 [ 0  0  0  0  0  2  1 50  1  0]
 [ 1  2  1  3  0  2  1  0 40  1]
 [ 0  0  0  0  0  1  1  1  2 45]]
              precision    recall  f1-score   support

           0       0.98      0.93      0.95        56
           1       0.83      0.75      0.79        59
           2       0.92      0.89      0.90        53
           3       0.84      0.79      0.82        62
           4       0.94      0.81      0.87        42
           5       0.79      0.90      0.84        62
           6       0.83      0.94      0.88        51
           7       0.91      0.93      0.92        54
           8       0.82      0.78      0.80        51
           9       0.80      0.90      0.85        50

    accuracy                           0.86       540
   macro avg       

### Random Forest

In [73]:
from sklearn.ensemble import RandomForestClassifier

random_forest = RandomForestClassifier(random_state=32)
random_forest.fit(X_train, y_train)
y_pred = random_forest.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[56  0  0  0  0  0  0  0  0  0]
 [ 0 59  0  0  0  0  0  0  0  0]
 [ 0  0 53  0  0  0  0  0  0  0]
 [ 0  0  1 58  0  1  0  2  0  0]
 [ 0  0  0  0 40  0  0  1  0  1]
 [ 0  0  0  0  0 60  0  0  0  2]
 [ 0  0  0  0  0  0 51  0  0  0]
 [ 0  0  0  0  0  0  0 54  0  0]
 [ 0  2  1  0  0  1  1  0 46  0]
 [ 0  0  0  0  0  1  0  0  0 49]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        56
           1       0.97      1.00      0.98        59
           2       0.96      1.00      0.98        53
           3       1.00      0.94      0.97        62
           4       1.00      0.95      0.98        42
           5       0.95      0.97      0.96        62
           6       0.98      1.00      0.99        51
           7       0.95      1.00      0.97        54
           8       1.00      0.90      0.95        51
           9       0.94      0.98      0.96        50

    accuracy                           0.97       540
   macro avg       

### SVM

In [75]:
from sklearn import svm

C = 20  # SVM regularization parameter

svm = svm.SVC(kernel='rbf', C=C)
svm.fit(X_train, y_train)
y_pred = svm.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[56  0  0  0  0  0  0  0  0  0]
 [ 0 59  0  0  0  0  0  0  0  0]
 [ 0  0 53  0  0  0  0  0  0  0]
 [ 0  0  0 61  0  1  0  0  0  0]
 [ 0  0  0  0 42  0  0  0  0  0]
 [ 0  0  0  0  0 61  0  0  0  1]
 [ 0  0  0  0  0  0 51  0  0  0]
 [ 0  0  0  0  0  0  0 54  0  0]
 [ 0  1  0  0  0  0  0  0 49  1]
 [ 0  0  0  0  0  1  0  0  0 49]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        56
           1       0.98      1.00      0.99        59
           2       1.00      1.00      1.00        53
           3       1.00      0.98      0.99        62
           4       1.00      1.00      1.00        42
           5       0.97      0.98      0.98        62
           6       1.00      1.00      1.00        51
           7       1.00      1.00      1.00        54
           8       1.00      0.96      0.98        51
           9       0.96      0.98      0.97        50

    accuracy                           0.99       540
   macro avg       

### SGD Classifier

In [42]:
from sklearn.linear_model import SGDClassifier

sgd = SGDClassifier(alpha=0.001, max_iter = 1000)
sgd.fit(X_train,  y_train)
y_pred = sgd.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.96      0.98        56
           1       0.91      0.90      0.91        59
           2       1.00      1.00      1.00        53
           3       0.98      0.92      0.95        62
           4       1.00      0.98      0.99        42
           5       0.84      0.98      0.90        62
           6       0.98      1.00      0.99        51
           7       0.98      0.96      0.97        54
           8       0.90      0.92      0.91        51
           9       0.98      0.90      0.94        50

    accuracy                           0.95       540
   macro avg       0.96      0.95      0.95       540
weighted avg       0.95      0.95      0.95       540



### Logistic Regression 

In [50]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression(multi_class="multinomial", max_iter= 2000)
logreg.fit(X_train, y_train)
y_pred = logreg.predict(X_test)

# Predict for One Observation (image)
# logreg.predict(x_test[0].reshape(1,-1))

print(classification_report(y_test, y_pred))

# Accuracy 
score = logreg.score(X_test, y_test)
print(score)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        56
           1       0.90      0.97      0.93        59
           2       1.00      0.98      0.99        53
           3       1.00      0.95      0.98        62
           4       1.00      0.98      0.99        42
           5       0.95      0.97      0.96        62
           6       0.98      1.00      0.99        51
           7       1.00      1.00      1.00        54
           8       0.92      0.86      0.89        51
           9       0.92      0.96      0.94        50

    accuracy                           0.97       540
   macro avg       0.97      0.97      0.97       540
weighted avg       0.97      0.97      0.97       540

0.9666666666666667


### 모델 평가